### PR TITLE
DM-13849: Convert all ap_verify test data to obs_test

### PR DESCRIPTION
**Pull request by kfindeisen**
This PR initializes `ap_verify_testdata` by replacing all files associated with `ap_verify_dataset_template`. There were a few template-isms that I overlooked at first (e.g., renaming the EUPS table file), so please look for things that should have been changed but weren't.

### CODE REVIEW

**Comment by kfindeisen** [comment]
The LSSTSim data from which the scripts worked are no longer available, and only existed on `lsst-dev` anyway. We'd have to store them on LFS somewhere.

(They might also be too slow, but I have no way of testing that 😉).

**Comment by mrawls** [comment]
Fair enough! You obviously managed to get ahold of it somehow, well done. In that case, I suggest updating the [obs_test data README](https://github.com/lsst/obs_test/blob/master/data/ReadMe.md) to point to these nicely generated files in case anyone in the future would like to use them.

**Comment by kfindeisen** [comment]
No, I didn't. I just used the (generated) files that are already already stored in `obs_test`. The readme is as up-to-date as I can make it.

**Comment by mrawls** [comment]
OK, I misunderstood, because I didn't see those files in obs_test/data initially, but I see them now. I'm trying to make sure we don't have lots of duplicate files floating around. Can you load the files directly from obs_test/data/input instead of having them live here too?

**Comment by kfindeisen** [comment]
I guess they could be included as part of the EUPS `setup` process? That's the only way I can think of that doesn't sound completely crazy.

**Comment by mrawls** [comment]
I guess I thought you could just import obs_test within ap_verify_testdata and access them that way, somehow? But it's probably not that straightforward. OK, well, don't let a few duplicate files stop you from moving ahead with this!

**Pull request merged**
